RedHatInsights/authz

- .github/workflows/golangci-lint.yml
- .golangci.yml
- cmd/authz/apiserver_test.go
- cmd/authz/main.go
This PR adds https://github.com/golangci/golangci-lint linting to the pipeline as a concurrent job as per their [GHa usage recommendation](https://github.com/golangci/golangci-lint-action#how-to-use).
It also adds a linting config based on the uber [go style guide](https://github.com/uber-go/guide/blob/master/style.md#linting) - only difference: I set the timeout for now to 2minutes, derived from playbook-dispatchers [use of this GHa](https://github.com/RedHatInsights/playbook-dispatcher/blob/master/.github/workflows/golangci-lint.yml)
The config file should be read as it is in the root of the repo, see [docs](https://golangci-lint.run/usage/configuration/#config-file)
> Add golangci-linter with default config derived by ubers go styleguide

- k8s/README.md
- k8s/kind.yml
This makes kind work with rootless podman. Otherwise you get:
```
ERROR: failed to create cluster: command "podman run --name authz-control-plane --hostname authz-control-plane --label io.x-k8s.kind.role=control-plane --privileged --tmpfs /tmp --tmpfs /run --volume 4a67ea7ee8272d79c3661af36c0951cad4f06be50ad08baa877af2f9402bb256:/var:suid,exec,dev --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --net kind --label io.x-k8s.kind.cluster=authz -e container=podman --volume /dev/mapper:/dev/mapper --device /dev/fuse --publish=0.0.0.0:80:80/tcp --publish=0.0.0.0:443:443/tcp --publish=127.0.0.1:62262:6443/tcp -e KUBECONFIG=/etc/kubernetes/admin.conf docker.io/kindest/node@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1" …
```
> Use non-privileged ports with kind

- .github/workflows/push-image.yml
If we want to add linux/arm64 platform image to the build.
> Add linux/arm64 platform image to build.

- api/buf.gen.yaml
- api/gen/v1/core.swagger.yaml
- api/v1/gw_openapi_mapping.yaml
- app/Errors.go
- app/Principal.go
- app/Principal_test.go
- app/controllers/Access.go
- host/GrpcServer.go
- host/Web_test.go
For status codes
- The gRPC service now sets response codes
- The 'controller' object is now in charge of whether an identity is required and checking for it
- There's a new Errors.go with sentinel error values
- The gRPC service will set different status codes depending on the exact error from below
- The gateway automatically translates gRPC response codes to HTTP status codes
- The web tests now assert the correct HTTP status codes
For documentation
- There's now a gw_openapi_mapping.yaml that provides additional data for the OpenAPI output
- I moved most of the hand-written OpenAPI info over to it to be included in future generated docs
> Updated gRPC service and swagger docs for correct HTTP response codes

- .gitignore
- Makefile
* includes existence- and matching version-check for underlying protoc/buf
* installs missing go binaries if needed
* backs up "old" generated code in genbackup/ before generating new one
* generates code using buf
* adds a few clean funcs to remove generated stuff
* adds genbackup/ to gitignore so it is not checked in.
> Make buf-gen target

- README.md
- infrastructure/repository/authzed/SpiceDbAccessRepository_test.go
This is a built-in Golang feature that allows a 'short' test run to be requested and sets a flag that tests can see (testing.Short()) and optionally shorten themselves, like by skipping, using a smaller dataset, or testing in a simplified way. This flag defaults to false leaving the full test run the default behavior, and tests can be aware of it on an opt-in basis (ex: tests that run an external container.)
> Added awareness of -short flag to enable fast test runs

- Makefile
- k8s/README.md
For the local dev setup, if you run `make kind-deploy` right after `make kind-create`, `make kind-deploy` fails when it tried to add the ingress for the authz service. The reason is that the nginx controller is not ready. (This takes almost a minute on my machine for some reason.) The change to the kind-create make target waits for the nginx controller to be in place.
Changes:
- Make target change as described, above.
- Small k8s README change to remove authz from path.
> Fixes for local development kind k8s setup

- api/http/Server_test.go
- application/AccessAppService.go
- application/LicenseAppService.go
- bootstrap/AccessRepositoryBuilder.go
- bootstrap/PrincipalRepositoryBuilder.go
- domain/contracts/AccessRepository.go
- domain/contracts/PrincipalRepository.go
- domain/contracts/SeatLicenseRepository.go
- domain/model/CheckEvent.go
- domain/model/ModifySeatAssignmentEvent.go
- domain/model/Principal.go
- domain/model/Principal_test.go
- domain/model/Request.go
- domain/services/AccessService.go
- domain/services/AccessService_test.go
- domain/services/SeatLicenseService.go
- domain/services/SeatLicenseService_test.go
- domain/valueobjects/SubjectID.go
- infrastructure/repository/authzed/SpiceDbAccessRepository.go
- infrastructure/repository/fga/OpenFgaAccessRepository.go
- infrastructure/repository/mock/StubAccessRepository.go
- infrastructure/repository/mock/StubPrincipalRepository.go
This one may have gotten a bit out of hand, but it's three commits that are aiming for three high-level goals:
- Making the placeholder authz logic inactive so it's out of the way but easy to implement in the future and the PrincipalRepository open to just-in-time test data (all Gets succeed)
- Removing the (incorrect) business logic around org membership and, since it's no longer needed, removing org information from the Principal domain model. The Org domain model wasn't removed yet but potentially could be.
- Trimmed down current use of the Principal domain model to a SubjectID value object since working with principals by reference is an important part of our domain. This also removes all (even simulated) interaction with external systems from the Check path.
> Slim use of principalrepository

- infrastructure/repository/authzed/SpiceDbAccessRepository.go
Renaming variables and cleanup
Add logging to help with debugging the errors
- Run Spicedb using the kind commands and schema
- Portward spicedb deployment to localhost:50051
``` ./authz serve --endpoint=localhost:50051 --token=<key-goes-here> --store=spicedb ```
Verify check permission end-point
``` curl -X POST localhost:8081/v1alpha/check -H "Content-Type: application/json" -H "Authorization: token" -d '{"subject": "u1", "operation": "access", "resourcetype": "license", "resourceid": "o1/smarts"}' ```
> renaming and cleaning check permission for spicedb impl

- api/http/Server_test.go
- application/LicenseAppService.go
- bootstrap/SeatLicenseRepositoryBuilder.go
- bootstrap/app.go
- infrastructure/repository/authzed/SpiceDbAccessRepository.go
Basic implementation for Assign/Unassing seat license for spicedb store
Fixed issues with seatlicense repo intialization
TODO: Can be follow-up PRs or tackled in separate sub-task/jira
- precondition/filters
- permission check
- add test for assigned/unassign
* Create Spicedb using kind commands in make file
* Port forward spicedb deployment 
* Run Authz service
`./authz serve --endpoint=localhost:50051 --token=spice-db-preshared-api-key-goes-here --store=spicedb
`
```
curl --location 'localhost:8081/v1alpha/orgs/aspian/licenses/smarts' \
--header 'Authorization: Bearer token' \
--header 'Content-Type: application/json' \
--data '{
"assign": [
"u7"
]
}'
```
```
curl --location 'localhost:8081/v1alpha/orgs/aspian/licenses/smarts' \
--header 'Authorization: Bearer token' \
--header …
```
> Intial implementation for seat assign/unassign in spicedb store

- bootstrap/app.go
The spiceDB connection downstream is broken, and trying this fix to gather more information.
Co-Authored-by: William Scalf
> Enable blocking to true for spiceDB grpc dial

- .github/pull_request_template.md
Done using [this](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) guide. 
Guess it has to be merged to see if it works for the next PR.
> initial DoD Template based on decided DoD Doc

- go.mod
- go.sum
- infrastructure/repository/authzed/SpiceDbAccessRepository.go
- bump authzed-go to 0.8 and fix deprecated function call. 
Fixes #
> bump authzed-go and fix deprecated function call

- api/grpc/Server.go
- api/grpc/interceptor/AuthnInterceptor.go
- api/grpc/interceptor/AuthnInterceptor_test.go
- We want to be able to support multiple issuers/OIDC providers in the AuthnInterceptor, to support various scenarios.
- An incoming bearer token will be validated against each configured provider until either a) one of them validates and introspects the token, or b) all providers are tried and none can/will validate the token.
Fixes #CIAM-5932
> Allows multiple issuers/providers to be supported in AuthnInterceptor

- api/grpc/Server.go
- api/grpc/interceptor/PassthroughAuthnInterceptor.go
- config.yaml
Introduces PassthroughInterceptor when all AuthConfigs are set to enabled:false
- introduce PassthroughInterceptor with static requestorID
- 
Fixes #
> Fix for the panic when no authconfig is given

- go.mod
- go.sum
superseeds dependabot PR as the structure of the go.mod file remains intact
errdetails now loaded from more specific packagae google.golang.org/genproto/googleapis/rpc so the whole genproto package is indirect
- ...
Fixes #
> Bump gateway to v2.16 and clean go.mod

- api/grpc/Server.go
- api/grpc/interceptor/AuthnInterceptor.go
- api/grpc/interceptor/AuthnInterceptor_test.go
- bootstrap/app_test.go
- config.yaml
- testenv/FakeIdp.go
- Extracting orgID and isOrgAdmin from auth token in addition to subjectID and setting in context.
- Add logic to seat admin grpc Server methods to return unauthorized when requestor is not an org admin for the org they are intending to assign seats for. 
- As is, this change will break our smoke test, since the authenticated user running the smoke test must be an org admin for the "o1" org in the environment (i.e. stage/prod) we're running the smoke test against. This is because the smoke test calls seat admin endpoints.
Fixes #CIAM-5756.
> Ciam 5756 seat admin meta auth z

- infrastructure/repository/authzed/SpiceDbAccessRepository.go
- infrastructure/repository/authzed/SpiceDbAccessRepository_test.go
- Added better logging to these operations. 
- Fixes the test `TestUnassignBatch` - I stumbled upon the fact that it did not batch-unassign at all, but just unassign one user. Was still green as we compare the count only.
- Could be improved way further by checking the error response and writing exact error reasons (e.g. "one user was inactive" or sth) - stayed away from this for another time (note for future improvers: extend`unwrapSpiceDbError` for these cases is imo the way to go here. ) 
Fixes #
> Improve logging for assign / unassign operation.

- bootstrap/app_test.go
- Bug: a GET/POST returning a non-200 error code will not benefit from a retry, and the attempt slows/hangs tests that do not return 200s.
Fixes #
> Stop tests retrying when non-200 http code returned

- scripts/test.sh
uses jq 'isnumber' buitin
- ...
Fixes #
> fix smoketest

- .github/workflows/codeql-analysis.yaml
* gives us more control, and ability to re-run. See this response: https://github.com/github/codeql/discussions/13703#discussioncomment-6416403
* commented yaml is taken from their standard generated template when choosing advanced mode
* change included: do not run analysis on changes that only affect md / txt files to spare some github minutes (we have 2000 free minutes, a run takes around 4min)
* change included: also run codeQL every 24h because even when code does not change, the database definition to check against may change
when this is merged, we should check settings if severity level still applies, could not find a way to define that in yaml
Fixes CIAM-6398
> Add CodeQL yaml for advanced mode

- bootstrap/app_test.go
to check if this removes the spurious 503s we see
- Summary: The tests were previously waiting for a response from the proxy server (no communication error) which waited for the proxy to be active but offered no assurance that the grpc server was. When the proxy comes up before the grpc server, this opens up tests to fail with 503s.
- also changes the endpoint that is checked from "check" to the newly introduced "healthcheck" endpoint 
Fixes CIAM-6405
* [] The Changes were automatically built, tested, and  - if needed, behind a feature flag - deployed to our production environment. (**Please check this when the new deployment is done and you could verify it.**)
* [-] For changes to the public API / code dependencies: Was the whole team (or a sufficient amount of ppl) able to review?
> changing retry behaviour to how it was before PR #183

- api/grpc/interceptor/AuthnInterceptor.go
- api/grpc/interceptor/AuthnInterceptor_test.go
- bootstrap/serviceconfig/ServiceConfig.go
- temporarily disable audience validation in interceptor until the environment has changed so this is actually useful.
Fixes #
> temporarily disable audience validation in interceptor

- application/AccessAppService.go
- application/LicenseAppService.go
- application/Validation.go
- application/Validation_test.go
- bootstrap/app_test.go
Added 'in' validator for constrained lists
Added 'service' and 'identifier' aliases
Decorated event/message structs with stricter rules
- Added 'in' validator for constrained lists
- Added 'service' and 'identifier' aliases
- Decorated event/message structs with stricter rules
Fixes #CIAM-6394
> Tighten up validation

- api/grpc/interceptor/AuthnInterceptor.go
- api/grpc/interceptor/AuthnInterceptor_test.go
- bootstrap/app_test.go
- bootstrap/serviceconfig/ServiceConfig.go
- testenv/FakeIdp.go
- re-introduce audience checking
- internal config is already set up with the right aud claim to check, it's just not used as we had problems getting the right audience
- adds a few tests so we make sure multiple audiences are used and parsed correctly, even if we switch the lib sometime in the future
Fixes #
* [-] For changes to the public API / code dependencies: Was the whole team (or a sufficient amount of ppl) able to review?
> Ciam 6318 reintroduce aud validation
