RedHatInsights/authz

cmd/authz/apiserver_test.go, cmd/authz/main.go
- Basic hello world HTTP server
- One test case to test the HTTP server
=> Basic hello world HTTP server

.github/workflows/workflow.yml, Dockerfile, cmd/authz/apiserver_test.go, cmd/authz/main.go, go.mod
on hold as long as quay stuff is not sorted out.
=> Initial CI workflow plus package naming bugfix

.github/workflows/workflow.yml
.. at least when I understand the [docs](https://github.com/docker/build-push-action#git-context) right
=> remove context from buildaction, should work now

cmd/authz/main.go
Basic code to test the HTTP(s) mode
=> Basic code to start the server in HTTP(s) mode if certs are found

k8s/README.md, k8s/authz.yml, k8s/kind.yml
readme instructions influenced by https://kind.sigs.k8s.io/docs/user/ingress/ and https://collabnix.com/kind-a-local-kubernetes-engine/
=> deployment.yml plus instructions for local deployment using kind

api/v1alpha/openapi-authz-v1_alpha.yaml
Fix the API spec - removed tags
=> Fix the the API spec

k8s/spicedb.yaml
- Adding basic single pod spicedb deployment k8s template
=> adding spicedb deployment spec

main.go
Added debug statements for testing authz-spiceDB connection
=> Add debug logs to test the spiceDB connection

api/grpc/Server.go, api/http/Server.go, bootstrap/app.go, k8s/authz.yml
- Move cert paths up into app.go.
- Small fix for kind config so the ingress takes the right url path.
=> Just some small fixes to config

application/LicenseAppService.go, infrastructure/repository/authzed/SpiceDbAccessRepository.go
JIRA Link: https://issues.redhat.com/browse/CIAM-5312
- Get license implementation in spiceDB repository
- Read License relationship
- Read and extract "max" count
- Read and extract "version" information
=> Get license implementation

infrastructure/repository/authzed/SpiceDbAccessRepository.go
- Increment version count during assign
- Decrement version count during un-assign
=> Update License version - implementation with assign and unassign

bootstrap/app.go, bootstrap/app_test.go
=> CIAM-5611: Get startup tested and all APIs working again

api/ServerConfig.go, bootstrap/AccessRepositoryBuilder.go, bootstrap/SeatLicenseRepositoryBuilder.go, bootstrap/app.go
=> Pass endpoint configuration via builders

api/http/Server.go, api/http/Server_test.go, go.mod, go.sum, scripts/test.sh
=> Ciam 5649 cors changes

go.mod, go.sum
dependabot did not find this for whatever reason
* [x ] Are the agreed upon acceptance criteria fulfilled?
* [x ] Do your changes have passing automated tests and sufficient observability?
* [ x] Are the work steps you introduced repeatable by others, either through automation or documentation?
* [x ] The Changes were automatically built, tested, and  - if needed, behind a feature flag - deployed to our production environment. (**Please check this when the new deployment is done and you could verify it.**)
* [ x] Are the agreed upon coding/architectural practices applied?
* [x ] Are security needs fullfilled? (e.g. no internal URL)
* [ x] Is the corresponding Ticket in the right state? (should be on "review" now, put to done when this change made it to production)
* [ x] For changes to …
=> bump glog to v1.1.1

api/http/Middleware.go, api/http/Middleware_test.go, api/http/Server.go
=> Adds basic request logging and simple middleware.

api/http/Server.go
=> add user-agent header to allowed slice

scripts/test.sh
=> add fake origin to script.sh

README.md, docs/development.md
=> Basic dev environment setup steps.

domain/Errors.go, domain/services/AccessService_test.go, domain/services/SeatLicenseService.go, domain/services/SeatLicenseService_test.go
=> Added TestSeatLicenseOverAssignment from collab.

.github/pull_request_template.md
=> Extend PR template: description and reference

api/http/Server_test.go, bootstrap/app_test.go, domain/services/AccessService_test.go, domain/services/SeatLicenseService_test.go
=> Update currently test-skipping

api/grpc/Server.go, api/http/Server_test.go, domain/services/SeatLicenseService_test.go
This continues the work from the earlier collab session, adding more test cases and taking the response all the way out to the client (currently returning FailedPrecondition on the gRPC side which translates to 400/bad request on the HTTP side- I spent some time looking into different options and none seemed to fit perfectly. We can def discuss.)
=> Continue license limits work

api/http/Server.go, api/http/Server_test.go
=> add tls handling to reverse proxy

api/http/Server.go
=> skip CA verification for inter-port-communication

README.md, scripts/test.sh
- Added OIDC Authorization Code flow login support to the smoketest. Usage directions are in the README
- Added an exit trap to the smoketest so that it will attempt to unassign the synthetic_test user if it exits while that user has a license assigned. This should prevent the sort of data pollution that causes the test suite to fail if it has failed and early-exited previously
Fixes #CIAM-5964
=> Smoketest updates

api/grpc/interceptor/AuthnInterceptor.go, api/grpc/interceptor/AuthnInterceptor_test.go
- Added test to ensure correct error returned when token invalid and not last issuer
- Added issuer peeking to select the correct authconfig
- Added bencmark to measure changes in token processing performance
- Added test to ensure correct error returned when token invalid and not last issuer
- Added issuer peeking to select the correct authconfig
- Added bencmark to measure changes in token processing performance
Fixes #
=> Issuer peeking 

bootstrap/app.go, config.yaml
This greatly reduces the required fields and focuses on things that vary between environments.
Fixes #
=> Initial pass at using defaults for configuration

Dockerfile, go.mod
- update go version to latest 1.20.5 for Dockerfile and 1.20 for go.mod
Fixes #
=> update go version to latest 1.20.5 for Dockerfile and 1.20 for go.mod

bootstrap/SubjectRepositoryBuilder.go, bootstrap/app.go, bootstrap/serviceconfig/ServiceConfig.go, infrastructure/repository/userservice/UserServiceSubjectRepository.go
=> Ciam 5494 user service repo impl

bootstrap/app.go, bootstrap/app_test.go, infrastructure/repository/userservice/UserServiceSubjectRepository.go, testenv/FakeUserServiceApi.go
- User Service implementation of PrincipalRepository. (Added new API call to UserServiceSubjectRepository.)
- Wired up new implementation instead of the stub PrincipalRepository. (Still falling back to the stub for SubjectRepository and PrincipalRepository.)
- Removed one test which relied on stub principal repository preloaded data.
Fixes #CIAM-6087.
=> CIAM-6087: User Service implementation of PrincipalRepository to enrich user data

bootstrap/serviceconfig/ServiceConfig.go, domain/contracts/MessageBusRepository.go, go.mod, go.sum, infrastructure/repository/messaging/SubjectEventMessage.go, infrastructure/repository/messaging/UMBMessageBusRepository.go, infrastructure/repository/messaging/UMBMessageBusRepository_test.go, testdata/activemq/bootstrap.xml, testdata/activemq/broker.xml, testdata/activemq/login.config, testdata/activemq/roles.properties, testdata/activemq/users.properties, testenv/LocalActiveMqContainer.go, testenv/LocalActiveMqContainer_test.go
=> Initial UMB repository, tests only

api/grpc/Server.go, bootstrap/app_test.go, bootstrap/serviceconfig/ServiceConfig.go, config.yaml, scripts/get-token.sh
- Added meta authz for entitle org and import org users endpoints, so that only whitelisted subjects can access them.
- Added a script to generate access token.
Fixes #CIAM-6258
=> Ciam 6258 meta authz entitle import

api/event/EventAdapter.go, api/events/EventAdapter.go, api/grpc/Server.go, application/LicenseAppService.go, application/LicenseAppService_test.go, bootstrap/app.go, domain/contracts/MessageBusRepository.go, domain/contracts/OrganizationRepository.go, domain/contracts/SeatLicenseRepository.go, infrastructure/repository/authzed/LocalSpiceDbContainer.go, infrastructure/repository/authzed/SpiceDbAccessRepository.go, infrastructure/repository/authzed/SpiceDbAccessRepository_test.go, infrastructure/repository/messaging/UMBMessageBusRepository.go, testenv/LocalActiveMqContainer.go
- Another UMB increment- it uses the events now!
Fixes #
=> Ciam 6101 integration into appservice

application/LicenseAppService.go
=> Fixed sending requests for no users

go.mod, go.sum
plus cleaning up unnecessary requires in go.mod
- ...
Fixes #
=> Bump protobuf to v1.31.0

api/grpc/Server.go, bootstrap/app_test.go, bootstrap/serviceconfig/ServiceConfig.go
- Added config for CheckWhitelist, which is a slice of subjects that are whitelisted for the check endpoint.
- Added check in Server.
- Added a test in app_test, fixed broken tests and removed a duplicate.
- Some discussion should be had before merge to see what additional manual/smoke testing we should do .
Fixes #CIAM-6297
=> Add whitelist authz to check endpoint.

scripts/test.sh
* introduces an orgId parameter to set the org which is used for tests
* introduces a userId parameter to set the userId that is tested.
* introduces a maxSeats parameter to set the maxSeats to check against initially
* adds a bit more logging aroung the tests to see what happens
* for example call see internal chat.
- ...
Fixes CIAM-6300
* [-] For changes to the public API / code dependencies: Was the whole team (or a sufficient amount of ppl) able to review?
=> Fixes the smoketest script.

api/grpc/Server.go, bootstrap/app_test.go, bootstrap/serviceconfig/ServiceConfig.go, config.yaml
- Change config field names from 'White'list to 'Allow'list
Fixes #
=> Update to allowlist

api/grpc/Server.go, application/AccessAppService.go, application/LicenseAppService.go, application/LicenseAppService_test.go, application/Validation.go, bootstrap/app_test.go, domain/Errors.go
- Added basic validation for api and event inputs
- Added some high-level tests to explore the responses
- Added some TODOs
- Added basic validation for api and event inputs
- Added some high-level tests to explore the responses
- Added some TODOs
Fixes #
=> Initial api validation

api/grpc/Server.go, api/grpc/interceptor/AuthnInterceptor.go, api/grpc/interceptor/ErrorConvertingInterceptor.go, api/grpc/interceptor/PassthroughAuthnInterceptor.go, application/AccessAppService.go, application/LicenseAppService.go, application/LicenseAppService_test.go, application/Validation.go, bootstrap/app.go, bootstrap/app_test.go, domain/services/SeatLicenseService_test.go
- Addressed TODOs from previous PR
- Removed unnecessary 'ok' return (Thanks @merlante)
- Use shared validator for config as well as requests/messages (Thanks @DGuhr)
- Require inputs to modifyseats to be unique
Fixes #CIAM-6394
* [*] Are the agreed upon acceptance criteria fulfilled?
* [*] Do your changes have passing automated tests and sufficient observability?
* [*] The Changes were automatically built, tested, and  - if needed, behind a feature flag - deployed to our production environment. (**Please check this when the new deployment is done and you could verify it.**)
* [*] Are the agreed upon coding/architectural practices applied?
* [*] Are security needs fullfilled? (e.g. no internal URL)
* [*] Is the corresponding Ticket in the right state? (should be on "review" now, put to …
=> Ciam 6394 api validation pt2

.github/workflows/push-image.yml
=> Remove ARM64

application/AccessAppService.go, application/LicenseAppService.go
=> Removed spicedb-id requirement from Requestor

scripts/get-token.sh
from openid to api.iam.access
- ...
Fixes #
=> Change default get-token scope

scripts/get-sa-token.sh
- Exercise the client credential grant flow
- Get the token for a service account
- ...
Fixes #
=> Add the get service account script

api/events/EventAdapter.go, bootstrap/app.go, bootstrap/serviceconfig/ServiceConfig.go, infrastructure/repository/messaging/UMBMessageBusRepository.go
=> Umb reconnects

.github/workflows/build-test.yml, .github/workflows/codeql.yml, .github/workflows/golangci-lint.yml, .github/workflows/push-image.yml
- Superseeds multiple automated PRs. 
Fixes #
=> update GHa versions to newest ones

.github/workflows/build-test.yml, .github/workflows/golangci-lint.yml, bootstrap/serviceconfig/ServiceConfig.go, go.mod, go.sum
=> update spicedb version to 1.26 + patch dep updates
